#!/bin/sh


################## get id from mac #####################
APID=`/sbin/ifconfig | grep eth0 | awk 'BEGIN{FS=" "}{print $5}' | awk 'BEGIN{FS=":"}{print $6}'`
APNAME=USINAS-AP-$APID
echo $APNAME

####set AP mode#######
/usr/sbin/uaputl.exe bss_stop > /dev/null
/usr/sbin/uaputl.exe sys_cfg_ssid $APNAME
#/usr/sbin/uaputl.exe sys_cfg_protocol 32
#/usr/sbin/uaputl.exe sys_cfg_cipher 4 4
#/usr/sbin/uaputl.exe sys_cfg_wpa_passphrase 1234567890
/usr/sbin/uaputl.exe bss_start

##########killall udhcpd ##########3

######set uap0 ip############
#APIDNUM=`echo "0x$APID" | awk '{printf "%u",$0}'`
#/sbin/ifconfig uap0 192.168.$APIDNUM.1
/sbin/ifconfig uap0 192.168.1.1


######set udhcpd.conf###########


########udhcpd########
/usr/sbin/udhcpd


